Tests
tobilg/mesos-framework pull request #5
Opened 2016-12-14 13:10 UTC by dudyk

Added unit tests to the project, about 40% coverage for now, with some skips of non critical tests (like name based task sort).

2016-12-14 13:43 UTC, tobilg requested changes

2016-12-14 13:43 UTC, tobilg commented on lib/scheduler.js
> +    self.options.frameworkName = (options.frameworkName || "mesos-framework." + uuid.v4()).replace(/ /g, "-");
Not sure why the replace was moved. There shouldn't be any space in a UUID, but in a framework name the can potentially be some... Please change it back.

2016-12-14 13:43 UTC, tobilg commented on lib/scheduler.js
> +            if (Object.getOwnPropertyNames(allowedEventHandlers).indexOf(ucHandlerName) > -1 && helpers.isFunction(options.handlers[handlerName]) && options.handlers[handlerName].length === allowedEv
Can you please explain why this is necessary?

2016-12-14 13:43 UTC, tobilg commented on lib/scheduler.js
> +        self.zkClient = options.zkClient || zookeeper.createClient(self.options.zkUrl);
Can you please explain why this is necessary?

2016-12-14 13:43 UTC, tobilg commented on lib/scheduler.js
> +        self.taskHelper = options.taskHelper || new TaskHelper(self);
Can you please explain why this is necessary?

2016-12-14 14:12 UTC, kohend commented on lib/scheduler.js
> +    self.options.frameworkName = (options.frameworkName || "mesos-framework." + uuid.v4()).replace(/ /g, "-");
If there is no framework name it fails with replace undefined since frameworkName is not a string, this is a simple change to make it pass no matter what, doing nothing if there's no framework name set.

2016-12-14 14:15 UTC, kohend commented on lib/scheduler.js
> +            if (Object.getOwnPropertyNames(allowedEventHandlers).indexOf(ucHandlerName) > -1 && helpers.isFunction(options.handlers[handlerName]) && options.handlers[handlerName].length === allowedEv
If there is a custom handler set as a non upper case name (a test was added with mixed case) it fails, this causes the comparison to be case insensitive.

2016-12-14 14:15 UTC, dudyk commented on lib/scheduler.js
> +        self.zkClient = options.zkClient || zookeeper.createClient(self.options.zkUrl);
For tests we need a way to inject a stub client.

2016-12-14 14:16 UTC, kohend commented on lib/scheduler.js
> +        self.taskHelper = options.taskHelper || new TaskHelper(self);
Injecting test object to run the unit tests.

2016-12-14 14:56 UTC, tobilg commented on lib/scheduler.js
> +    self.options.frameworkName = (options.frameworkName || "mesos-framework." + uuid.v4()).replace(/ /g, "-");
I think it'd be ok if it fails then... The default value can't have a space char even IMO, so I guess it doesn't really make sense to add the replace there.

2016-12-14 14:57 UTC, tobilg commented on lib/scheduler.js
> +        self.zkClient = options.zkClient || zookeeper.createClient(self.options.zkUrl);
Then this would also need to be documented...

2016-12-14 14:57 UTC, tobilg commented on lib/scheduler.js
> +        self.taskHelper = options.taskHelper || new TaskHelper(self);
Then this would also need to be documented...

2016-12-14 17:23 UTC, dudyk commented on lib/scheduler.js
> +    self.options.frameworkName = (options.frameworkName || "mesos-framework." + uuid.v4()).replace(/ /g, "-");
Fails as in the constructor crashes...
It's either this or change it to an actual if sentence, do you think that's better?

2016-12-15 11:44 UTC, tobilg commented on lib/scheduler.js
> +    self.options.frameworkName = (options.frameworkName || "mesos-framework." + uuid.v4()).replace(/ /g, "-");
I think we should throw an error in case the `frameworkName` is null...

2016-12-15 11:44 UTC, tobilg commented on lib/scheduler.js
> +            if (Object.getOwnPropertyNames(allowedEventHandlers).indexOf(ucHandlerName) > -1 && helpers.isFunction(options.handlers[handlerName]) && options.handlers[handlerName].length === allowedEv
OK...!

2016-12-15 20:36 UTC, tobilg approved these changes

2016-12-15 20:37 UTC, merged